- hosts: "{{ server }}"
  become: true
  become_user: root
  tasks:
    - name: Upgrade all packages
      yum: name=* state=latest update_cache=yes 

    - name: Get Docker script
      shell: curl -fsSL https://get.docker.com/ | sh

    - name: Enable Docker service
      command: systemctl enable docker.service

    - name: Start Docker service
      command: systemctl start docker
