- hosts: "{{ server }}"
  become: true
  become_user: root
  tasks:
    - name: Yum update
      command: yum update

    - name: Install latest Docker version
      command: curl -fsSL https://get.docker.com/ | sh

    - name: Enable Docker service
      command: systemctl enable docker.service

    - name: Start Docker service
      command: systemctl start docker