- hosts: localhost
  connection: local
  vars:
    vcenter_hostname:
    vcenter_user: 
    vcenter_pass: 
    vm_name:
    template:
    datacenter:
    cluster:
    resource_pool:
    esxi:
    folder:
  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        validate_certs: False
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ vm_name }}"
        from_template: yes
        template_src: "{{ template }}"
        cluster: "{{ cluster }}"
        resource_pool: "{{ resource_pool }}"
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi }}"
        vm_extra_config:
          notes: Created by Ansible
          folder: "{{ folder }}"