- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_hostname: 
    vcenter_user: 
    vcenter_pass:
    vm_to_delete:
  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        validate_certs: False
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ vm_to_delete }}"
        state: absent
        force: yes